apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xwebsites.unnefer.com
spec:
  claimNames:
    kind: Website
    plural: websites
  group: unnefer.com
  names:
    categories:
    - websites
    - composition
    - crossplane
    kind: XWebsite
    plural: xwebsites
  versions:
  - name: v1alpha1
    additionalPrinterColumns:
    - description: The main domain for the website.
      jsonPath: .spec.parameters.domain.name
      name: Domain
      type: string
    - description: The on/off switch for the website.
      jsonPath: .spec.parameters.enabled
      name: Enabled
      type: boolean
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                description: website configuration parameters.
                properties:
                  region:
                    type: string
                    description: Region is the region youre bucket is located.
                  bucket:
                    description: "The initial bucket for the first required Origin. A distribution requires at least one origin.\n At the bare minimum a Website can simply server static files from a bucket."
                    properties:
                      name:
                        description: The name of the bucket with a static website.
                        type: string
                      path:
                        description: The path to the root dir in the Bucket which includes the main index.html
                        type: string
                      forceDestroy:
                        description: Boolean that indicates all objects (including any locked objects) should be deleted from the bucket when the bucket is destroyed so that the bucket can be destroyed without error. These objects are not recoverable. This only deletes objects when the bucket is destroyed, not when setting this parameter to true. If setting this field in the same operation that would require replacing the bucket or destroying the bucket, this flag will not work.
                        type: boolean
                    type: object
                  defaultRootObject:
                    default: index.html
                    description: The name of the file to load by default when the URL does not specify one.
                    type: string
                  description:
                    description: A descriptive blurb about what this Website is for.
                    type: string
                  domain:
                    description: domain configuration field
                    properties:
                      name:
                        description: domain name for a-record in zone
                        type: string
                      zoneId:
                        description: zoneId of the hosted zone to place your domain name.
                        type: string
                    type: object
                  enabled:
                    default: true
                    description: True when the distribution is active. Set to false before deleting a distribution.
                    type: boolean
                  tags:
                    description: Map of additional AWS Tags to add to resources
                    additionalProperties:
                      type: string
                    type: object
              deletionPolicy:
                type: string
                description: DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either "Delete" or "Orphan" the external resource.
              providerConfigRef:
                type: object
                description: crossplane provider credentials to use.
                properties:
                  name:
                    type: string
                required:
                - name
            required:
            - parameters
            - deletionPolicy
            - providerConfigRef
          status:
            properties:
              s3:
                description: Useful values generated from the S3 API.
                type: object
                x-kubernetes-preserve-unknown-fields: true
                type: object
              certificate:
                description: Useful values generated from the ACM API.
                type: object
                x-kubernetes-preserve-unknown-fields: true
              cloudfront:
                description: Useful values generated from the CloudFront API.
                type: object
                x-kubernetes-preserve-unknown-fields: true
            type: object
