# upload-static-content-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: upload-static-content
  labels:
    app: static-website
spec:
  template:
    spec:
      containers:
      - name: aws-cli
        image: amazon/aws-cli:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            git clone --depth 1 https://github.com/shlomigonen/unnefer-website.git /repo && \
            aws s3 sync /repo/static-site-files s3://unnefer-website-public-s3-bucket/ --acl public-read
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: aws_secret_access_key
        volumeMounts:
        - name: github-ssh
          mountPath: /root/.ssh
      restartPolicy: OnFailure
      volumes:
      - name: github-ssh
        secret:
          secretName: github-ssh-key # Add a secret for private repo access (optional)
  backoffLimit: 4
